Update and rewrite datatilstander
statisticsnorway/dapla-manual-legacy pull request #129
Opened 2023-11-07 12:29 UTC by akcssb

Complete rewrite of datatilstander-page.

2023-11-07 20:01 UTC, skars82 requested changes
Jeg likte veldig godt oppsettet. Har bare noen småkommentarer som jeg tenker bør fikses før vi merger

2023-11-07 20:01 UTC, skars82 commented on dapla-manual/datatilstander.qmd
> +##### <span style="color:black;"> 1. Kildedata </span>
Jeg skjønner ikke helt hensikten med å hardkode inn html her. Lenken finnes jo i innholdfortegnelsen. Synes vi bør endre det til å være en vanlig markdown-liste.

2023-11-07 20:01 UTC, skars82 commented on dapla-manual/datatilstander.qmd
> +![Figur 1: Datatilstander](images/datatilstander.png){fig-alt="Datatilstander" width="100%"}
Fint med denne figuren, men vi ønsker ikke å hardkode inn figur-nummer. Du kan se hvordan de andre bildene er kodet inn i andre kapitler og endre det.

2023-11-07 20:01 UTC, skars82 commented on dapla-manual/references.bib
>  @unpublished{datatilstander,
Hvorfor har du fjernet informasjon fra referansene?

2023-11-07 20:01 UTC, skars82 commented on dapla-manual/datatilstander.qmd
> +-----
Litt rart med den linjen. Vi bruker det ikke noe annet sted. Er det et virkemiddel du ønsker å benytte?

2023-11-08 12:42 UTC, akcssb commented on dapla-manual/datatilstander.qmd
> +##### <span style="color:black;"> 1. Kildedata </span>
Det er mest for å få svart farge - blir litt irritert av gråfargen. Men kan fint fjerne det:)

2023-11-08 12:43 UTC, akcssb commented on dapla-manual/references.bib
>  @unpublished{datatilstander,
Ikke meningen! Fjernet først referansen og så la jeg den tilbake

2023-11-08 12:43 UTC, akcssb commented on dapla-manual/datatilstander.qmd
> +-----
Kan fint fjerne det og, tenkte bare det var pent å skille metadatadelen fra datatilstandene.

2023-11-08 20:00 UTC, skars82 requested changes
Veldig bra. Bare en liten kommentar om lister

2023-11-08 20:00 UTC, skars82 commented on dapla-manual/datatilstander.qmd
> +##### <span style="color:black;"> 1. Kildedata </span>
Jeg tenker at det er fint om vi bruker markdown-lister som vi gjør ellers i manualen. Ikke bruke h4-headere.

2023-11-09 20:03 UTC, skars82 approved these changes
Nydelig

2023-11-09 20:03 UTC, merged