Write chapter installing packages with python
statisticsnorway/dapla-manual-legacy pull request #2
Opened 2022-10-20 12:32 UTC by Andilun

First draft of "Virtuelle miljøer" and "Installere pakker".

2022-10-21 07:55 UTC, mmwinther commented on dapla-manual/pakke-install.qmd
> +b) Undersøk prosjektets tilknyttede repository. Tilhører det en kjent organisasjon (f.eks. [SSB](https://github.com/statisticsnorway))?
I think this can be overly confusing for users, there are many popular packages which aren't connected to a well known brand. I think points a) and c) are enough advice.

2022-10-21 07:57 UTC, mmwinther approved these changes, later dismissed
LGTM

2022-10-21 08:45 UTC, Andilun commented on dapla-manual/pakke-install.qmd
> +b) Undersøk prosjektets tilknyttede repository. Tilhører det en kjent organisasjon (f.eks. [SSB](https://github.com/statisticsnorway))?
Good point, removed.

2022-10-24 06:35 UTC, mmwinther requested changes

2022-10-24 06:35 UTC, mmwinther commented on docs/search.json
> +    STAT-131-dokumentere-løsningen
I think this line is left over from the merge process and should be deleted

2022-10-24 06:59 UTC, mmwinther approved these changes
Nice one 👍

2022-10-24 07:05 UTC, merged